### ISSUE TITLE
gradle 5.1.1 support

### ISSUE THREAD

**Issue by lukas-vlcek** [vvanholl/elasticsearch-prometheus-exporter#153]
Elasticsearch [upgraded to gradle 5.1.1](https://github.com/elastic/elasticsearch/pull/37410)
Plugin code does not work with this version of gradle yet (still it works fine with gradle 4.10.3):
```
$ gradle clean

> Configure project :
=======================================
Elasticsearch Build Hamster says Hello!
  Gradle Version        : 5.1.1
  OS Info               : Mac OS X 10.14.2 (x86_64)
  JDK Version           : 11 (Oracle Corporation 11.0.1 [Java HotSpot(TM) 64-Bit Server VM 11.0.1+13-LTS])
  JAVA_HOME             : /Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home
  Random Testing Seed   : 4B15A0F48F843A51
=======================================
Host: MacBook-Pro/10.43.21.123
Gradle: 5.1.1 JVM: 11.0.1 (Oracle Corporation 11.0.1+13-LTS) Groovy: 2.5.4
Build: group: 'org.elasticsearch.plugin.prometheus', name: 'prometheus-exporter', version: '6.5.4.1-SNAPSHOT'
Timestamp: 2019-01-21T11:03:59.478214+01:00[Europe/Prague]

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'prometheus-exporter'.
> No value has been specified for this provider.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s
```
`gradle clean --stacktrace` reveals some details:
```
* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring root project 'prometheus-exporter'.
        at org.gradle.configuration.project.LifecycleProjectEvaluator.wrapException(LifecycleProjectEvaluator.java:79)
...
Caused by: java.lang.IllegalStateException: No value has been specified for this provider.
        at org.gradle.api.internal.provider.Providers$1.get(Providers.java:32)
```

**Comment by atorok** [comment]
Gradle `5.0` broke this version of build tools, so I'm afraid you will have to continue using Gradle `4.10` fir this version. We switched to Gradle `5.1.1` with `6.6` so it will start working again with that version.

**Comment by lukas-vlcek** [comment]
@atorok Thanks for the info.

**Comment by lukas-vlcek** [comment]
I am going to close this ticket now.

Just for the track record: Starting with ES 6.6 (see https://github.com/vvanholl/elasticsearch-prometheus-exporter/pull/161) we need to switch to Gradle 5.1.1 (or higher) from 4.10.3.
