### ISSUE TITLE
Reported memory used inconsistent

### ISSUE THREAD

**Issue by pkaramol** [vvanholl/elasticsearch-prometheus-exporter#157]
We have installed the plugin in our cluster running `elasticsearch 6.4.2`

However there seems to be an inconsistency between the metrics reported by the plugin and the actual system metrics.

e.g. it indicates an ~99% mem usage, which does not seem to be the case.

this is from one of our `data` nodes in the cluster:

```
curl -s 11.11.11.211:9200/_prometheus/metrics | grep -i es_os_mem_used_bytes
# HELP es_os_mem_used_bytes Memory used
# TYPE es_os_mem_used_bytes gauge
es_os_mem_used_bytes{cluster="my-cluster",node="elastic-data2-stg",nodeid="U5v44hjnQO2X_JtuqFwMQg",} 6.5165877248E10

curl -s 111.11.11.211:9200/_prometheus/metrics | grep -i es_os_mem_used_percent
# HELP es_os_mem_used_percent Memory used in percent
# TYPE es_os_mem_used_percent gauge
es_os_mem_used_percent{cluster="my-cluster",node="elastic-data2-stg",nodeid="U5v44hjnQO2X_JtuqFwMQg",} 99.0


root@ip-10-17-17-200:~# free -hm
              total        used        free      shared  buff/cache   available
Mem:            61G         33G        791M        788K         27G         27G
Swap:            0B          0B          0B

```

**Comment by chentaichuang** [comment]
total 92
-rw-r--r-- 1 elk elk 87192 Jul  3 13:18 elasticsearch-prometheus-exporter-6.4.2.0.zip
[elk@csx-dev-redis-monitor plugins]$ sh /elk/elasticsearch/bin/elasticsearch-plugin install file:///elk/elasticsearch/plugins/elasticsearch-prometheus-exporter-6.4.2.0.zip 

-> Downloading file:///elk/elasticsearch/plugins/elasticsearch-prometheus-exporter-6.4.2.0.zip
[=================================================] 100%   
Exception in thread "main" java.lang.IllegalStateException: Could not load plugin descriptor for plugin directory [elasticsearch-prometheus-exporter-6.4.2.0.zip]
        at org.elasticsearch.plugins.PluginsService.readPluginBundle(PluginsService.java:394)
        at org.elasticsearch.plugins.PluginsService.findBundles(PluginsService.java:379)
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:372)
        at org.elasticsearch.plugins.InstallPluginCommand.jarHellCheck(InstallPluginCommand.java:755)
        at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:727)
        at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:792)
        at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:775)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:231)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:216)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
Caused by: java.nio.file.FileSystemException: /elk/elasticsearch/plugins/elasticsearch-prometheus-exporter-6.4.2.0.zip/plugin-descriptor.properties: Not a directory
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
        at java.nio.file.Files.newInputStream(Files.java:152)
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:162)
        at org.elasticsearch.plugins.PluginsService.readPluginBundle(PluginsService.java:391)
        ... 14 more



nohup: ignoring input
[2019-07-04T18:33:49,803][INFO ][o.e.n.Node               ] [node1] initializing ...
[2019-07-04T18:33:49,990][INFO ][o.e.e.NodeEnvironment    ] [node1] using [1] data paths, mounts [[/ (rootfs)]], net usable_space [42.8gb], net total_space [49gb], types [rootfs]
[2019-07-04T18:33:49,990][INFO ][o.e.e.NodeEnvironment    ] [node1] heap size [1007.3mb], compressed ordinary object pointers [true]
[2019-07-04T18:33:49,991][INFO ][o.e.n.Node               ] [node1] node name [node1], node ID [O_U_6d4mRMSEgYinNgY77g]
[2019-07-04T18:33:49,991][INFO ][o.e.n.Node               ] [node1] version[6.4.2], pid[10064], build[default/tar/04711c2/2018-09-26T13:34:09.098244Z], OS[Linux/3.10.0-693.el7.x86_64/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_201/25.201-b09]
[2019-07-04T18:33:49,992][INFO ][o.e.n.Node               ] [node1] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/tmp/elasticsearch.UmYPLTFT, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -XX:+PrintGCDetails, -XX:+PrintGCDateStamps, -XX:+PrintTenuringDistribution, -XX:+PrintGCApplicationStoppedTime, -Xloggc:logs/gc.log, -XX:+UseGCLogFileRotation, -XX:NumberOfGCLogFiles=32, -XX:GCLogFileSize=64m, -Des.path.home=/elk/elasticsearch, -Des.path.conf=/elk/elasticsearch/config, -Des.distribution.flavor=default, -Des.distribution.type=tar]
[2019-07-04T18:33:50,046][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [node1] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Could not load plugin descriptor for plugin directory [elasticsearch-prometheus-exporter-6.4.2.0.zip]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:140) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.4.2.jar:6.4.2]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.4.2.jar:6.4.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) ~[elasticsearch-6.4.2.jar:6.4.2]
Caused by: java.lang.IllegalStateException: Could not load plugin descriptor for plugin directory [elasticsearch-prometheus-exporter-6.4.2.0.zip]
        at org.elasticsearch.plugins.PluginsService.readPluginBundle(PluginsService.java:394) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.plugins.PluginsService.findBundles(PluginsService.java:379) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:372) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:144) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.node.Node.<init>(Node.java:315) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.node.Node.<init>(Node.java:256) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:326) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-6.4.2.jar:6.4.2]
        ... 6 more
Caused by: java.nio.file.FileSystemException: /elk/elasticsearch/plugins/elasticsearch-prometheus-exporter-6.4.2.0.zip/plugin-descriptor.properties: Not a directory
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[?:?]
        at java.nio.file.Files.newByteChannel(Files.java:361) ~[?:1.8.0_201]
        at java.nio.file.Files.newByteChannel(Files.java:407) ~[?:1.8.0_201]
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384) ~[?:1.8.0_201]
        at java.nio.file.Files.newInputStream(Files.java:152) ~[?:1.8.0_201]
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:162) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.plugins.PluginsService.readPluginBundle(PluginsService.java:391) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.plugins.PluginsService.findBundles(PluginsService.java:379) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:372) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:144) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.node.Node.<init>(Node.java:315) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.node.Node.<init>(Node.java:256) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:326) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-6.4.2.jar:6.4.2]
        ... 6 more

**Comment by lukas-vlcek** [comment]
@chentaichuang Please do not mix topics in single ticket.

Where did you download the plugin from? The exception is about missing plugin description file. When I download official release I can see the description file is included.
```
$ wget https://github.com/vvanholl/elasticsearch-prometheus-exporter/releases/download/6.4.2.0/elasticsearch-prometheus-exporter-6.4.2.0.zip
[...]
$ unzip elasticsearch-prometheus-exporter-6.4.2.0.zip 
Archive:  elasticsearch-prometheus-exporter-6.4.2.0.zip
  inflating: elasticsearch-prometheus-exporter-6.4.2.0.jar  
  inflating: simpleclient_common-0.4.0.jar  
  inflating: simpleclient-0.4.0.jar  
  inflating: plugin-descriptor.properties  
  inflating: plugin-security.policy  
```

**Comment by chentaichuang** [comment]
Thank you very much for your reply!


At present, my problem has arrived, which is due to my installation mode. According to the installation mode on GitHub, it can be installed.

Example:

Install
Since Elasticsearch 7.0.0 : ./bin/elasticsearch-plugin install -b https://github.com/vvanholl/elasticsearch-prometheus-exporter/releases/download/7.1.1.0/prometheus-exporter-7.1.1.0.zip

Since Elasticsearch 6.0.0 : ./bin/elasticsearch-plugin install -b https://github.com/vvanholl/elasticsearch-prometheus-exporter/releases/download/6.8.0.0/prometheus-exporter-6.8.0.0.zip

On Elasticsearch 5.x.x : ./bin/elasticsearch-plugin install -b https://github.com/vvanholl/elasticsearch-prometheus-exporter/releases/download/5.6.16.0/elasticsearch-prometheus-exporter-5.6.16.0.zip

On old 2.x.x versions : ./bin/plugin install https://github.com/vvanholl/elasticsearch-prometheus-exporter/releases/download/2.4.1.0/elasticsearch-prometheus-exporter-2.4.1.0.zip


[elk@chuang2 plugins]$ ll
总用量 88
-rw-r--r-- 1 elk elk 87192 7月   3 13:18 elasticsearch-prometheus-exporter-6.4.2.0.zip
[elk@chuang2 plugins]$ 
[elk@chuang2 plugins]$ 
[elk@chuang2 plugins]$ sh /elk/elasticsearch-6.4.2/bin/elasticsearch-plugin install -b https://github.com/vvanholl/elasticsearch-prometheus-exporter/releases/download/6.4.2.0/elasticsearch-prometheus-exporter-6.4.2.0.zip    
-> Downloading https://github.com/vvanholl/elasticsearch-prometheus-exporter/releases/download/6.4.2.0/elasticsearch-prometheus-exporter-6.4.2.0.zip
[=================================================] 100%   
Exception in thread "main" java.lang.IllegalStateException: Could not load plugin descriptor for plugin directory [elasticsearch-prometheus-exporter-6.4.2.0.zip]
        at org.elasticsearch.plugins.PluginsService.readPluginBundle(PluginsService.java:394)
        at org.elasticsearch.plugins.PluginsService.findBundles(PluginsService.java:379)
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:372)
        at org.elasticsearch.plugins.InstallPluginCommand.jarHellCheck(InstallPluginCommand.java:755)
        at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:727)
        at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:792)
        at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:775)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:231)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:216)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
Caused by: java.nio.file.FileSystemException: /elk/elasticsearch-6.4.2/plugins/elasticsearch-prometheus-exporter-6.4.2.0.zip/plugin-descriptor.properties: 不是目录
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
        at java.nio.file.Files.newInputStream(Files.java:152)
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:162)
        at org.elasticsearch.plugins.PluginsService.readPluginBundle(PluginsService.java:391)
        ... 14 more
[elk@chuang2 plugins]$ 
[elk@chuang2 plugins]$ ll
总用量 88
-rw-r--r-- 1 elk elk 87192 7月   3 13:18 elasticsearch-prometheus-exporter-6.4.2.0.zip
[elk@chuang2 plugins]$ rm -fr elasticsearch-prometheus-exporter-6.4.2.0.zip 
[elk@chuang2 plugins]$ 
[elk@chuang2 plugins]$ 
[elk@chuang2 plugins]$ sh /elk/elasticsearch-6.4.2/bin/elasticsearch-plugin install -b https://github.com/vvanholl/elasticsearch-prometheus-exporter/releases/download/6.4.2.0/elasticsearch-prometheus-exporter-6.4.2.0.zip 
-> Downloading https://github.com/vvanholl/elasticsearch-prometheus-exporter/releases/download/6.4.2.0/elasticsearch-prometheus-exporter-6.4.2.0.zip
[=================================================] 100%   
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessClassInPackage.sun.misc
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.reflect.ReflectPermission suppressAccessChecks
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
-> Installed prometheus-exporter

**Comment by lukas-vlcek** [comment]
Please [open a new ticket](https://github.com/vvanholl/elasticsearch-prometheus-exporter/issues/new) for this. Thanks for understanding.
