### ISSUE TITLE
Unable to install 7.9.3 - missed plugin-descriptor.properties file

### ISSUE THREAD

**Issue by Firm** [vvanholl/elasticsearch-prometheus-exporter#298]
(as root)
/usr/share/elasticsearch/bin/elasticsearch-plugin install -b https://github.com/vvanholl/elasticsearch-prometheus-exporter/archive/7.9.3.0.tar.gz
-> Installing https://github.com/vvanholl/elasticsearch-prometheus-exporter/archive/7.9.3.0.tar.gz
-> Downloading https://github.com/vvanholl/elasticsearch-prometheus-exporter/archive/7.9.3.0.tar.gz
-> Failed installing https://github.com/vvanholl/elasticsearch-prometheus-exporter/archive/7.9.3.0.tar.gz
-> Rolling back https://github.com/vvanholl/elasticsearch-prometheus-exporter/archive/7.9.3.0.tar.gz
-> Rolled back https://github.com/vvanholl/elasticsearch-prometheus-exporter/archive/7.9.3.0.tar.gz
Exception in thread "main" java.nio.file.NoSuchFileException: /usr/share/elasticsearch/plugins/.installing-950131543450009953/plugin-descriptor.properties
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:375)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:426)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:160)
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:156)
	at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:807)
	at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:866)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:254)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:224)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:91)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)

**Comment by Firm** [comment]
My bad, https://github.com/vvanholl/elasticsearch-prometheus-exporter/releases/download/7.9.3.0/prometheus-exporter-7.9.3.0.zip is the correct link.
