### ISSUE TITLE
Elasticsearch 2.4.0 compatible package

### ISSUE THREAD

**Issue by knweiss** [vvanholl/elasticsearch-prometheus-exporter#4]
Could you please provide a package compatible with Elasticsearch **2.4.0**?

I just started a rolling-upgrade from ES 2.3.5 to 2.4.0 on my test cluster and the first node fails during startup with the following error message:
```
[2016-09-01 11:01:50,988][ERROR][bootstrap                ] Exception
java.lang.IllegalArgumentException: Plugin [prometheus-exporter] is incompatible with Elasticsearch [2.4.0]. Was designed for version [2.3.5]
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:118)
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:378)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:128)
        at org.elasticsearch.node.Node.<init>(Node.java:158)
        at org.elasticsearch.node.Node.<init>(Node.java:140)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:194)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:286)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
```

So, I had to disable the prometheus-exporter temporarily.

**Comment by vvanholl** [comment]
Version 2.4.0.0 has just been released.

**Comment by knweiss** [comment]
I've just updated and it seems to work fine (just a couple of minutes though).

**Comment by knweiss** [comment]
I think you can close this issue. Thanks!
