### ISSUE TITLE
Could not find plugin class. version 2.4.1

### ISSUE THREAD

**Issue by iMelnik** [vvanholl/elasticsearch-prometheus-exporter#6]
Installed plugin within this Dockerfile
https://github.com/commercetools/docker-elasticsearch-kubernetes/blob/a7f5b4e9b1596dd650ae55c5ae4601df5626c907/Dockerfile
Build log: https://hub.docker.com/r/imelnik/docker-elasticsearch-kubernetes/builds/brzpwudjamraxdechd5xnak/

Other plugins seem bo work fine this way.
ES Version: 2.4.1
Plugin Version 2.4.1.0

```
2016-10-10T14:19:56.912502418Z [2016-10-10 14:19:56,911][INFO ][node                     ] [Marsha Rosenberg] version[2.4.1], pid[14], build[c67dc32/2016-09-27T18:57:55Z]
2016-10-10T14:19:56.912601670Z [2016-10-10 14:19:56,912][INFO ][node                     ] [Marsha Rosenberg] initializing ...
2016-10-10T14:19:57.666756004Z Exception in thread "main" ElasticsearchException[Could not find plugin class [org.elasticsearch.plugin.prometheus.PrometheusExporterPlugin]]; nested: ClassNotFoundException[org.elasticsearch.plugin.prometheus.PrometheusExporterPlugin];
2016-10-10T14:19:57.666847786Z Likely root cause: java.lang.ClassNotFoundException: org.elasticsearch.plugin.prometheus.PrometheusExporterPlugin
2016-10-10T14:19:57.667031174Z  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
2016-10-10T14:19:57.667071579Z  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2016-10-10T14:19:57.667151415Z  at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
2016-10-10T14:19:57.667163731Z  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2016-10-10T14:19:57.667217839Z  at org.elasticsearch.plugins.PluginsService.loadPluginClass(PluginsService.java:463)
2016-10-10T14:19:57.667280618Z  at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:431)
2016-10-10T14:19:57.667322592Z  at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:129)
2016-10-10T14:19:57.667344989Z  at org.elasticsearch.node.Node.<init>(Node.java:158)
2016-10-10T14:19:57.667392522Z  at org.elasticsearch.node.Node.<init>(Node.java:140)
2016-10-10T14:19:57.667430781Z  at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
2016-10-10T14:19:57.667490911Z  at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:194)
2016-10-10T14:19:57.667502420Z  at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:286)
2016-10-10T14:19:57.667588931Z  at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
2016-10-10T14:19:57.667600980Z Refer to the log for complete error details.
```

Any ideas on how do I fix that?

**Comment by vvanholl** [comment]
Hi,

I have tried and I have also the same issue.
In fact command "RUN /elasticsearch/bin/plugin install vvanholl/elasticsearch-prometheus-exporter/2.4.1.0 --verbose"  does not install the plugin itself but the sources :

```
/elasticsearch/plugins/prometheus-exporter # ls
LICENSE.txt                   plugin-descriptor.properties  pom.xml
README.md                     plugin-security.policy        src
```

That's really weird, I am currently investigating on it.

**Comment by vvanholl** [comment]
I have a partial answer :

When you launch
`/elasticsearch/bin/plugin install vvanholl/elasticsearch-prometheus-exporter/2.4.1.0 --verbose`
The plugin manager lookups on several sources in this order : elastic repo, maven repo, github repo

In my case, when comes github repo, the url tested are not from github releases, but from source code. This is good when it's a site plugin, But messy for java plugins :(

I should move my releases to Maven repo. waiting for that you could simply reuse the url, specified in the README.md
`https://github.com/vvanholl/elasticsearch-prometheus-exporter/releases/download/2.4.1.0/elasticsearch-prometheus-exporter-2.4.1.0.zip`

**Comment by iMelnik** [comment]
Thanks, I would try later on 👍
