### ISSUE TITLE
Unable to install on Easticsearch 6.2.0 with plugin-descriptor.properties, Unknown properties in plugin descriptor: [jvm, site]

### ISSUE THREAD

**Issue by HristoMohamed** [vvanholl/elasticsearch-prometheus-exporter#87]
``[root@elasticsearch01 bin]# /usr/share/elasticsearch/bin/elasticsearch-plugin install https://distfiles.compuscene.net/elasticsearch/elasticsearch-prometheus-exporter-6.2.0.0.zip
-> Downloading https://distfiles.compuscene.net/elasticsearch/elasticsearch-prometheus-exporter-6.2.0.0.zip
[=================================================] 100%   
Exception in thread "main" java.lang.IllegalArgumentException: Unknown properties in plugin descriptor: [jvm, site]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:284)
	at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:571)
	at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:707)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:623)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:223)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:212)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:75)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:48)
``

I downloaded, unzip and removed the lines jvm=true site=false and then it installed properly and works as well. 
I don't see the jvm=true and  site=false on the elastic official site https://www.elastic.co/guide/en/elasticsearch/plugins/current/plugin-authors.html#_plugin_descriptor_file

**Comment by davidkarlsen** [comment]
@vvanholl can you merge and do a new release?
